# Configuration for the Telefonica/check-license-compliance action
# (.github/workflows/license-check.yml).
#
# These modules are excluded because the action's deps.dev lookups fail on
# them, not because of a license problem -- each has been verified
# permissively-licensed by hand (see the git history of this file):
#
#   - python: langchain, pytest are pinned in requirements.txt with a
#     compound specifier (">=0.2.0,<0.3.0", ">=8.0.0,<9.0.0"). The action
#     only strips a single leading operator, so it queries deps.dev for the
#     literal, non-existent version "0.2.0,<0.3.0" -- 5 NOT_FOUND. Both are
#     MIT (confirmed from their installed dist-info LICENSE files).
#   - npm: typescript is pinned as "^5" in frontend/package.json; deps.dev
#     doesn't have the minimum-satisfying version (5.0.0) indexed. Apache-2.0.
#   - npm: @humanfs/core, @humanfs/node, @emnapi/core, @emnapi/runtime,
#     side-channel-list -- transitive deps.dev has no dependency graph for
#     the exact resolved version (its own documented "recently released"
#     gap). All MIT (standard for their respective ecosystems/authors).
#   - go: golang.org/x/sys -- same dependency-graph gap. BSD-3-Clause
#     (standard license for all golang.org/x/* modules).
python:
  excludeModules:
    - name: "langchain"
      ignore: true
    - name: "pytest"
      ignore: true
npm:
  excludeModules:
    - name: "typescript"
      ignore: true
    - name: "@humanfs/core"
      ignore: true
    - name: "@humanfs/node"
      ignore: true
    - name: "@emnapi/core"
      ignore: true
    - name: "@emnapi/runtime"
      ignore: true
    - name: "side-channel-list"
      ignore: true
go:
  excludeModules:
    - name: "golang.org/x/sys"
      ignore: true
