name: Documentation Check

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]
    paths:
      - "**/*.md"
      - ".github/workflows/docs-check.yml"
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - "**/*.md"
      - ".github/workflows/docs-check.yml"

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8  # v2.9.0
        with:
          args: --verbose --no-progress "**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
